# Generated by Django 2.2.4 on 2021-05-23 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0002_authors_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='desc',
            field=models.TextField(null=True),
        ),
    ]
